export const appText = {
  brand: 'форма',
  registered: '®',
  tagline: 'вещи для жизни',
  navigation: 'Основная навигация',
  orders: 'Мои заказы',
  cart: 'Корзина ',
  newSession: 'Начать новую гостевую сессию',
  unavailableTitle: 'Магазин пока недоступен',
  unavailableHint: 'Попробуйте загрузить каталог ещё раз.',
  emptyTitle: 'Здесь пока пусто.',
  emptyHint: 'Добавьте в корзину что-нибудь для хорошего дня.',
  browse: 'Посмотреть вещи',
  back: 'К коллекции',
  checkoutTitle: 'Ваши хорошие вещи.',
  checkoutHint: 'Ещё пара деталей — и заказ готов.',
  footer: 'Простые вещи. Каждый день.',
  edition: 'Учебный магазин · 2026',
} as const;
