export const ordersText = {
  paid: 'Оплачен',
  cash: 'Оплата при получении',
  processing: 'Ожидаем оплату',
  failed: 'Оплата не прошла',
  cancelled: 'Оплата отменена',
  unpaid: 'Не оплачен',
  eyebrow: 'ВАШИ ПОКУПКИ',
  title: 'Мои заказы.',
  description: 'Все ваши хорошие вещи — в одном месте.',
  refreshing: 'Обновляем…',
  refresh: 'Обновить статусы',
  emptyTitle: 'Заказов пока нет.',
  emptyHint: 'После оформления ваш первый заказ появится здесь.',
  browse: 'К коллекции',
  list: 'Список заказов',
  orderPrefix: 'Заказ ',
  courier: 'Курьерская доставка',
  pickup: 'Самовывоз',
  openOrder: 'Открыть заказ ',
  details: 'Подробнее',
  disclaimer: 'История заказов этой гостевой сессии. Сохраняется в этом браузере.',
} as const;
