export const orderText = {
  back: 'Мои заказы',
  eyebrow: 'ЗАКАЗ / ',
  opening: 'Открываем…',
  retryPayment: 'Повторить оплату',
  openPayment: 'Открыть форму оплаты',
  paymentEyebrow: 'ТЕСТОВАЯ ОПЛАТА',
  sending: 'Отправляем…',
  retryAction: 'Повторить выбранное действие',
  pay: 'Оплатить ',
  cancelPayment: 'Отменить оплату',
  verifying: 'Подтверждаем заказ…',
  processing: 'Обрабатываем платёж…',
  refresh: 'Обновить статус заказа',
  returnToProducts: 'Вернуться к вещам',
  returnToCatalog: 'Вернуться в каталог',
  summary: 'Состав и стоимость вашего заказа',
  quantitySuffix: ' шт.',
  delivery: 'Доставка',
  total: 'Итого',
  courierPrefix: 'Курьер: ',
  pickupPrefix: 'Самовывоз: ',
} as const;
